# Generated by Django 6.0 on 2026-01-25 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='converterfile',
            options={'verbose_name': 'Upload de Excel', 'verbose_name_plural': 'Uploads de Excel'},
        ),
    ]
