# Generated by Django 6.0 on 2026-02-01 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0003_bradescofile_milleniumfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='MilleniumExtraction',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('source_pdf', models.CharField(max_length=512)),
                ('extracted_file', models.CharField(blank=True, max_length=512, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
