# Generated by Django 6.0 on 2025-12-27 20:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otpcode',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='resetpasswordtoken',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='otpcode',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_codes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='resetpasswordtoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reset_tokens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='otpcode',
            index=models.Index(fields=['code'], name='authenticat_code_8d6738_idx'),
        ),
        migrations.AddIndex(
            model_name='otpcode',
            index=models.Index(fields=['user', 'is_used'], name='authenticat_user_id_3a8198_idx'),
        ),
    ]
