# Generated by Django 6.0 on 2025-12-30 16:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_usersession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersession',
            name='session_id',
        ),
        migrations.AddField(
            model_name='usersession',
            name='last_seen',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
