# Generated by Django 6.0 on 2025-12-30 18:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_remove_usersession_session_id_usersession_last_seen_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resetpasswordtoken',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='otpcode',
            name='authenticat_code_8d6738_idx',
        ),
        migrations.RemoveIndex(
            model_name='otpcode',
            name='authenticat_user_id_3a8198_idx',
        ),
        migrations.RemoveField(
            model_name='usersession',
            name='created_at',
        ),
        migrations.AddField(
            model_name='usersession',
            name='session_id',
            field=models.CharField(default=0, max_length=64, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='otpcode',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='resetpasswordtoken',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='resetpasswordtoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='ip_address',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='user_agent',
            field=models.TextField(blank=True, default=''),
        ),
    ]
