# Generated by Django 6.0 on 2026-01-01 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bancocredential',
            old_name='password_encrypted',
            new_name='secret_encrypted',
        ),
    ]
